[package]
name = "rust-ethereum-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.4"
ethers = "1.0.2"
eyre = "0.6.8"
hex = "0.4.3"
tokio = "1.24.2"
